import { useEffect, useState } from 'react'
import { Link } from 'react-router-dom'
import { getPosts } from '../api.js'

export default function Articles() {
  const [posts, setPosts] = useState(null)
  const [error, setError] = useState('')

  useEffect(() => {
    getPosts().then(setPosts).catch((err) => setError(err.message))
  }, [])

  return (
    <section className="articles-page">
      <div className="articles-heading">
        <div>
          <span className="eyebrow">The archive</span>
          <h1>Published articles</h1>
          <p>Select an article to read it and see the three tags generated by Gemma.</p>
        </div>
        <Link className="new-story-button" to="/">+ New story</Link>
      </div>

      {error && <div className="error" role="alert">{error}</div>}

      {!error && posts === null && (
        <div className="loader compact" aria-label="Loading"><span /><p>Loading articles…</p></div>
      )}

      {posts?.length === 0 && (
        <div className="empty-state">
          <span>✦</span>
          <h2>No stories yet</h2>
          <p>Publish your first article and it will appear here.</p>
          <Link className="articles-button" to="/">Write the first story →</Link>
        </div>
      )}

      {posts?.length > 0 && (
        <div className="article-grid">
          {posts.map((post, index) => (
            <Link className="article-card" to={`/posts/${post.id}`} key={post.id}>
              <span className="article-number">{String(index + 1).padStart(2, '0')}</span>
              <div>
                <h2>{post.title}</h2>
                <p>{post.description}</p>
              </div>
              <span className="read-link">Read & view tags <b>→</b></span>
            </Link>
          ))}
        </div>
      )}
    </section>
  )
}
